esphome:
  name: crescet
  platform: ESP32
  board: esp32dev
  on_boot:
    then:
      - script.execute: consider_deep_sleep

# Enable logging
#logger:

# Enable Home Assistant API
api:

ota:
  password: "ota-password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  domain: .mylocal

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "moisture-1 Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

#
# Run for 10 seconds (see delay in script)
# Deep sleep for 1 hour
#
deep_sleep:
  id: deep_sleep_control
  sleep_duration: 1h

sensor:
  - platform: adc
    pin: A3
    name: "Soil Moisture 1"
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: A6
    name: "Soil Moisture 2"
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0
  
  - platform: adc
    pin: A7
    name: "Soil Moisture 3"
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0
  
  - platform: adc
    pin: A4
    name: "Soil Moisture 4"
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0


  - platform: ultrasonic
    trigger_pin: 26
    echo_pin: 27
    name: "Ultrasonic Sensor"

  - platform: dht
    pin: 25
    temperature:
      name: "Fuse Box Temperature"
    humidity:
      name: "Fuse Box Humidity"

switch:
  - platform: gpio
    pin: 22
    name: "Pump 1"

  - platform: gpio
    pin: 1
    name: "Pump 2"

  - platform: gpio
    pin: 3
    name: "Pump 3"

  - platform: gpio
    pin: 21
    name: "Pump 4"

# Sensor in Home Automation that we are using to 
# stop Deep Sleep so we can watch the logs or
# perform OTA.
binary_sensor:
  - platform: homeassistant
    id: prevent_deep_sleep
    entity_id: input_boolean.prevent_deep_sleep

# Every 15 this script seconds check if "Prevent Deep Sleep" 
# isn't "On", go to deep sleep sleep.
# During that 15 seconds normal operations occur including
# sending sensor data. 
# If this time is too small. prevent_deep_sleep won't 
# necessarily be updated and data may not be sampled/sent.
script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - delay: 15s
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - logger.log: "Staying awake because Prevent Deep Sleep is on."
          else:
            - logger.log: "Taking a nap."
            - deep_sleep.enter: deep_sleep_control
      - script.execute: consider_deep_sleep